[options]
admin_passwd = rh_2026
db_host = postgres
db_port = 5432
db_user = odoo
db_password = odoo_strong_password
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
logfile = /var/log/odoo/odoo-server.log
log_level = info
log_handler = :INFO